import movies33 from "../../images/movies-33-words.png"
export const moviesData = [
  {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 1,
  },
   {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 2,
  },
  {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 3,
  },
   {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 4,
  },
  {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 5,
  },
   {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 6,
  },
  {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 7,
  },
   {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 8,
  },
  {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 9,
  },
   {
    country: 'Россия',
    duration: 1.2,
    image: "https://thumbs.dfs.ivi.ru/storage2/contents/9/4/782f1d6e00299c9cee37d8f733bdca.jpg",
    nameRU:"33 слова о дизайне",
    nameEN:"33 words about design",
    thumbnail: movies33,
    trailerLink:"https://www.youtube.com/watch?v=__2oZSM1l1Q",
    id: 10,
  },
]
